### ISSUE TITLE
Suggestions do not update search bar

### ISSUE THREAD

**Issue by hamzashahid-blit** [WardPearce/Materialious#109]
**Describe the bug**
Clicking on a suggestion does not update the search bar.

**To Reproduce**
1. Go to [materialio.us](materialio.us)
2. Type anything into the search bar without hitting enter.
3. Click on any suggestion.

**Expected behavior**
The search bar should update and the search should start.

Thank you for the amazing application and kind cooperation.

Regards,
Hamza

**Comment by hamzashahid-blit** [comment]
Also, am I being annoying posting this many issues? If you want I will stop. It was just a few things I found to make the project more polished a bit quicker so I could use this as my daily alternative.

**Comment by WardPearce** [comment]
> Also, am I being annoying posting this many issues? If you want I will stop. It was just a few things I found to make the project more polished a bit quicker so I could use this as my daily alternative to YouTube.

haha nah bring all the issues!
