### ISSUE TITLE
URL updates too late for accidental video click

### ISSUE THREAD

**Issue by hamzashahid-blit** [WardPearce/Materialious#110]
**Describe the bug**
Clicking on a video does not change the url for a few seconds until the video is loaded to some extent. If this was an accidental click, clicking back on the browser goes too far back instead of back to the search page.

**To Reproduce**
1. Go to [materialio.us](materialio.us).
2. Search anything.
3. Click on a video and almost immediately go back (with the help of the browser).
4. See error; Instead of going back to the search page, it goes back too far.

**Expected behavior**
Go back to search page.

**RECOMMENDATIONS**
Change the URL on click instead of waiting for the page to load and use appropriate error handling.

**Desktop**
 - OS: `Linux hamzas-pc 6.6.23_1 #1 SMP PREEMPT_DYNAMIC Thu Mar 28 23:12:50 UTC 2024 x86_64 GNU/Linux`
 - Browser: Firefox 124.0.1-1 (64-bit) (technically Librewolf which is a fork of Firefox)

Thank you for the amazing application and kind cooperation.

Regards,
Hamza

**Comment by WardPearce** [comment]
The `Thumbnail.svelte` component uses `data-sveltekit-preload-data="off"` to prevent sveltekit preloading video data (causing it to be added to the watch history) what isn't wanted.

With this disabled, videos take a bit longer to load. For whatever reason not updating the URL on page change until said page has loaded is standard Sveltekit behavior.

I'll keep this issue open until some solution is found.

**Comment by hamzashahid-blit** [comment]
Will try and fix this once I am free, you should probably focus on the other issues.

**Comment by WardPearce** [comment]
This is expected behaviour of Sveltekit apparently, possibly could speed up load times using https://svelte.dev/blog/streaming-snapshots-sveltekit
