### ISSUE TITLE
Delay in playing/pausing media player

### ISSUE THREAD

**Issue by hamzashahid-blit** [WardPearce/Materialious#112]
**Describe the bug**
When playing or pausing the video, there is a delay before it actually plays or pauses the media player (be it from the keyboard using the spacebar or clicking on the video).

THIS DOES **NOT** OCCUR WHEN: directly playing or pausing by clicking on the small button in the bottom left of the media player.

**To Reproduce**
1. Start playing any video on [materialio.us](materialio.us)
2. Use the spacebar OR click the media player (ANYWHERE EXPECT THE BUTTON AT THE BOTTOM LEFT) to play or pause the video.
3. See the delay?

Regards,
Hamza

**Comment by WardPearce** [comment]
How many seconds would you describe the delay? Don't notice anything myself. Also this is most likely a downstream issue with https://github.com/vidstack/player

**Comment by hamzashahid-blit** [comment]
Around 1 second. NOTE HOWEVER: 

> THIS DOES NOT OCCUR WHEN: directly playing or pausing by clicking on the small button in the bottom left of the media player.

**Comment by WardPearce** [comment]
Yea not experiencing myself on Firefox or Chrome. Maybe open a issue with Vidstack.
