### ISSUE TITLE
Infinite channel videos!

### ISSUE THREAD

**Issue by hamzashahid-blit** [WardPearce/Materialious#119]
**Describe the bug**
Scrolling through a channel gives infinite videos which loop back much like #107.

**To Reproduce**
1. Go to any channel on [materialio.us](materialio.us)
2. Scroll down to the bottom until more videos load.
3. See error; looping of videos.

**Screenshots**
Note the publishing dates of the videos.
![20240412_17h53m11s_grim](https://github.com/WardPearce/Materialious/assets/90385569/7f24f3b5-9106-4af9-81a8-288fa405c141)

I find it really amazing how many issues you have fixed in such a short amount of time. Much love.

Regards,
Hamza

**Comment by WardPearce** [comment]
Good catch! Fixed via #120. Thank you for helping to improve Materialious!

**Comment by hamzashahid-blit** [comment]
Thank you and my pleasure! :smile:
