### ISSUE TITLE
Preview video title with hover

### ISSUE THREAD

**Issue by hamzashahid-blit** [WardPearce/Materialious#126]
**Problem**
The full title of a video is usually "ellipsized" (truncated with the help of three full-stops) and to check the full title, you need to click on the video and wait for it load (still looking at you #110 (I think I will only get time for that after May :tired_face:))

**Recommended Solution(s)**
1. Please increase the limit before truncation WITH RESPECT TO screen size and number of columns if that is customizable.
2. Ideally, show the full title on hover. 

I am a professional tester of this project at this point lmao.

Regards,
Hamza

**Comment by WardPearce** [comment]
haha you very much are
