### ISSUE TITLE
Search focus - Chrome

### ISSUE THREAD

**Issue by arcoast** [WardPearce/Materialious#130]
Currently if I load up materialious in the browser, I need to click in the search box to get focus (no issue there).
Then when I've finished typing I need to again click in the search box to get focus "again" before I can hit enter to actually perform the search.

I think there are two possible improvements, and either would be wonderful.

 - have the search box in focus automatically on page load, enabling a user to type, hit enter all without using the mouse/touchpad
 - retain the current need to enable focus in the search box before typing but lose the requirement to then click in it again to get focus before pressing return to perform the search

**Comment by WardPearce** [comment]
Good catch, appears to be a issue with Chrome. As It appears to work as expected on Firefox

**Comment by arcoast** [comment]
> Good catch, appears to be a issue with Chrome. As It appears to work as expected on Firefox

Ah, my bad, I am actually currently using a Chromium based browser, instead of mt more usual Firefox, I should have tested, apologies!

**Comment by WardPearce** [comment]
> > Good catch, appears to be a issue with Chrome. As It appears to work as expected on Firefox
> 
> Ah, my bad, I am actually currently using a Chromium based browser, instead of mt more usual Firefox, I should have tested, apologies!

Nah good catch, my fault for not testing on Chrome

**Comment by arcoast** [comment]
Thanks @WardPearce confirmed as fixed for me.
