### ISSUE TITLE
Video Player cropped on ultrawide

### ISSUE THREAD

**Issue by PBogi** [WardPearce/Materialious#133]
First of all thanks for the great design!

I have a minor issue on my ultrawide screen: The content scales with the width of the viewport, so the video is cut off at the bottom.
This happens in normal and theatre mode. Resizing the window of course helps but it would be great, if the content also scales with height or has a maximum overall width.

![materialous-screen1](https://github.com/WardPearce/Materialious/assets/8455974/d9e17bc6-efc0-4a5c-ad30-f2c2d649bc90)
![materialous-screen2](https://github.com/WardPearce/Materialious/assets/8455974/4bad2979-dcf9-46e9-b185-d3d2306054de)

**Comment by WardPearce** [comment]
Appears to be fixed via #135 with a simulated ultra wide. Let me know if it resolved your issue & we can close this issue.

**Comment by PBogi** [comment]
Oh wow, that was quick, thank you! Unfortunately the video itself is now cropped.
[materialous.webm](https://github.com/WardPearce/Materialious/assets/8455974/4dc189c7-238e-4242-afb7-3448183007f3)

**Comment by WardPearce** [comment]
aah thats a oversight, good catch.
