### ISSUE TITLE
Favicon of website is not transparent

### ISSUE THREAD

**Issue by hamzashahid-blit** [WardPearce/Materialious#138]
Right now it looks like this:
![20240413_01h31m04s_grim](https://github.com/WardPearce/Materialious/assets/90385569/335b81ab-e9d8-45f5-89ff-288bea718266)

I have done this change and you can access the transparent bg version [here](https://files.catbox.moe/if4pea.png).
 
Regards,
Hamza

**Comment by WardPearce** [comment]
Is related to #122
