### ISSUE TITLE
Returning error on subscriptions and playlist tab after login in.

### ISSUE THREAD

**Issue by Exw27** [WardPearce/Materialious#16]
Console Log:
```Access to fetch at 'https://invidious.private.coffee/api/v1/auth/feed?max_results=100&page=1' from origin 'http://0.0.0.0:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.```

The statement is not true since following the link gives all the sucbscription data correctly.

![image](https://github.com/WardPearce/Materialious/assets/51909835/c9cc46d9-e385-41a9-8d04-5ca2c56c039f)

**Comment by WardPearce** [comment]
Please read the setup guide around CORS
https://github.com/WardPearce/Materialious?tab=readme-ov-file#setup
