### ISSUE TITLE
Use lower resolution thumbnails

### ISSUE THREAD

**Issue by ItzYanick** [WardPearce/Materialious#187]
**Describe the bug**
Currently it downloads all Thumbnails as maxres.jpg which are unnecesary large. Using mqdefault.jpg would reduce loading by a huge amount

**Comment by WardPearce** [comment]
Yea good idea, I'll modify https://github.com/WardPearce/Materialious/blob/main/materialious/src/lib/misc.ts#L138 to use the best thumbnail with consideration of its size. Maybe the thumbnail size should be customisable in setttings too.
