### ISSUE TITLE
Time ago field is wrong

### ISSUE THREAD

**Issue by ItzYanick** [WardPearce/Materialious#189]
**Describe the bug**
Above the video description, next to the view count is a time field that shows when the video was published. This is displayed wrong tho. The Screenshots show A. YouTube itself and B. Materialious for the same video.

A:
![A](https://github.com/WardPearce/Materialious/assets/18502828/8ef1c8d2-2ee8-4cbb-beaa-58c8ded09562)

B:
![B](https://github.com/WardPearce/Materialious/assets/18502828/dcf994ec-6b78-43f7-8ba0-311c84c3c7c6)

If I would guess this is a timezone bug. I am in Europe/Berlin if this helps

**Comment by WardPearce** [comment]
> **Describe the bug** Above the video description, next to the view count is a time field that shows when the video was published. This is displayed wrong tho. The Screenshots show A. YouTube itself and B. Materialious for the same video.
> 
> A: ![A](https://private-user-images.githubusercontent.com/18502828/326901064-8ef1c8d2-2ee8-4cbb-beaa-58c8ded09562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDgwMDUsIm5iZiI6MTcxNDUwNzcwNSwicGF0aCI6Ii8xODUwMjgyOC8zMjY5MDEwNjQtOGVmMWM4ZDItMmVlOC00Y2JiLWJlYWEtNThjOGRlZDA5NTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDIwMDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YzM0NGUwM2Y0ODQ3OWY1YzQ1NmMzMWNmNDBkNWUzMmVlMmNhMDIzY2I0ZGQxZTQyMTVkMzNkNGU1YmRiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FEufd9kqshCx4DIDUSUUMuaSY8yrrD4Zt-W766v5vfE)
> 
> B: ![B](https://private-user-images.githubusercontent.com/18502828/326901107-dcf994ec-6b78-43f7-8ba0-311c84c3c7c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MDgwMDUsIm5iZiI6MTcxNDUwNzcwNSwicGF0aCI6Ii8xODUwMjgyOC8zMjY5MDExMDctZGNmOTk0ZWMtNmI3OC00M2Y3LThiYTAtMzExYzg0YzNjN2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDIwMDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NWNlMjJhZDgxMTBkYjYyZmIxODg0ZTljNWY0ZGMyMGMzMzhiMDZhMjkxM2YyNjJlYWZjMDk1M2U1YTY1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aQaUTULdm_ORNHImIIzCMlNQLKHYiyiDmkOkx3qq3Iw)
> 
> If I would guess this is a timezone bug. I am in Europe/Berlin if this helps

is this the hosted instance of Materialious?

**Comment by ItzYanick** [comment]
Nope my own instance and my own invidious

**Comment by WardPearce** [comment]
Odd, is the time the same in Invidious?

**Comment by WardPearce** [comment]
Looking over Materialious code, we pull the publish date directly from Invidious' API `{data.video.publishedText}`, so it isn't a Materialious issue

**Comment by ItzYanick** [comment]
interesting. i have been debugging it now and i have no clue why invidious outputs its this way even tho the frontend of invidious shows it correct and even yattee shows it correct. well... thanks anyway

**Comment by WardPearce** [comment]
> interesting. i have been debugging it now and i have no clue why invidious outputs its this way even tho the frontend of invidious shows it correct and even yattee shows it correct. well... thanks anyway

Must be a bug with Invidious API, is very odd.
