### ISSUE TITLE
Feature request: YT-like paths

### ISSUE THREAD

**Issue by duoi** [WardPearce/Materialious#20]
Hello,

**Issue:** Currently the paths follow non-standard YT construction. For example, the Materialious video path is `/watch/wjZofJX0v4M` vs. `/watch?v=wjZofJX0v4M`.

**Impact:** It's typical add URL redirectors that do something to the effect of `*youtube.com/*` -> `	https://alternative.instance/$2` to capture YouTube URLs and forward them on. In this case, it would lead to dead paths.

**Request:** This request is to have the router adjusted to mimic the YT paths or to capture the YT standard path and introduce a redirection to the correct Materialious path.

Thank you

**Comment by WardPearce** [comment]
Fixed via #23
