### ISSUE TITLE
Bug: Subscribe button not disabled when logged out

### ISSUE THREAD

**Issue by duoi** [WardPearce/Materialious#21]
Hello,

**Issue**: Currently the `subscribe` button is not disabled when a user is logged out.

**Impact**: It's still possible to click the button, but it doesn't do anything or give any feedback.

**Proposed solution**: 

1. Introduce `isLoggedIn` or similar to determine login state.
```
import { auth } from '../../store';
let isLoggedIn = false;
auth.subscribe((value) => {
    isLoggedIn = value !== null;
});
```

3. Apply this to both the `subscribe` and the `add to playlist` buttons (which currently just check for `personalPlaylists` being `undefined`).
4. Add `login required` tooltip when the disabled state is active

**Comment by WardPearce** [comment]
Fixed via #23
