### ISSUE TITLE
Bug: Likes/dislikes with no decimal place are rendered with a zero decimal place

### ISSUE THREAD

**Issue by duoi** [WardPearce/Materialious#22]
Hello,

**Issue**: Currently YT likes or dislikes with no decimal place are still given one.

**Impact**: It's more visible on `<=999` counts, where the output looks like `27.0`.

**Proposed solution**:

Have the `cleanNumber` function in `misc.js` to call the below function or return the value with similar logic:

```
const omitDecimal = (value) => value % 1 === 0 ? parseInt(value) : value
```

Alternatively omit or replace `parseFloat` with `parseInt` in the `cleanNumber` function as the return yt dislikes API always returns integers [as per the docs](https://returnyoutubedislikeapi.com/swagger/index.html).

**Comment by WardPearce** [comment]
Fixed via #23
