### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by R0GGER** [WardPearce/Materialious#24]
I am using NGINX Proxy Manager with Invidious and Materialious...

I get this error in Materialious;
![image](https://github.com/WardPearce/Materialious/assets/8298741/1b6bdcd8-2c76-4401-a8fa-a6c4a6bf9268)

**Comment by WardPearce** [comment]
This is probably due to "domain" not being configured in Invidious' config

https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L98

**Comment by R0GGER** [comment]
Closed?
Not solved... domain didn't help. Cors issue remains.

**Comment by WardPearce** [comment]
If you provide the related network responses so i can assist further

**Comment by Provider2436** [comment]
> Closed? Not solved... domain didn't help. Cors issue remains.

I had the same issue as you, and I don't clearly remember what I changed but you can check my compose file here: https://github.com/Provider2436/Docker-compose-files/tree/main/Invidious

**Comment by R0GGER** [comment]
@Provider2436 Thanks! That helps...

I think these three are the fix:
```
        external_port: 443
        domain: your.domain.com
        https_only: true
```
