### ISSUE TITLE
Settings improvements

### ISSUE THREAD

**Issue by nargacu83** [WardPearce/Materialious#35]
Hi!

It would be nice to see the settings from Invidious being used in Materialious. This would also mean to be able to change some settings in Materialious.

Here are a few improvements:

- Preferred video / dash quality

  Right now every video i play is starting in `Auto` quality when i reload the page.

- Default player volume

  Every video starts at 100% of the volume, it would be nice to have the ability to change it to what i used in Invidious.

**Comment by WardPearce** [comment]
Yup agreed, this is a must have.

**Comment by WardPearce** [comment]
Volume is now saved once changed on player.
When a quality is selected this will be the default for all videos (or the closet quality to it).

Please note, currently it doesn't appear Vidstack loads volume correctly for dash. So rn volume can't be restored.
