### ISSUE TITLE
[Suggestion] Hide the time display for videos without a time

### ISSUE THREAD

**Issue by BentiGorlich** [WardPearce/Materialious#36]
On invidious I am able to remove shorts from being displayed by filtering for the time to be missing
```
invidious.io##div.pure-u-md-1-4.pure-u-1:has(.bottom-right-overlay):not(:has(.length))
```
I cannot do the same on materialious, because it puts a `00:00` there instead of just not having the time display:

| invidious | materialious |
| --------- | ------------ |
| ![grafik](https://github.com/WardPearce/Materialious/assets/25664458/9d6091b4-eb5d-4b52-986e-a2c04344a9f6) | ![grafik](https://github.com/WardPearce/Materialious/assets/25664458/95e40256-b99e-4ee6-983d-23beca203964) |

**Comment by WardPearce** [comment]
Yes good idea, shorts aren't the only videos without lengths tho.

**Comment by BentiGorlich** [comment]
Thats fine. Afaik thats only premieres and streams which do not work for me anyway 😅

**Comment by WardPearce** [comment]
Completed via #40
