### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Umfs** [WardPearce/Materialious#37]
After login into the invidious account, the Material UI does not show subscriptions as if it wasn't logged in.

**Comment by WardPearce** [comment]
Will need you to share network traffic from browser

**Comment by Umfs** [comment]
> share network traffic from browser

Sorry can you let me know how to share network traffic?

**Comment by WardPearce** [comment]
Via chrome dev tools or Firefox dev tools under the network tab

**Comment by WardPearce** [comment]
have u configured your reverse proxy as mentioned here https://github.com/WardPearce/Materialious?tab=readme-ov-file#setup

**Comment by Umfs** [comment]
> have u configured your reverse proxy as mentioned here https://github.com/WardPearce/Materialious?tab=readme-ov-file#setup

No. I simply followed this tutorial which uses Synology's builtin reverse proxy. https://mariushosting.com/how-to-install-materialious-on-your-synology-nas/

**Comment by WardPearce** [comment]
> > have u configured your reverse proxy as mentioned here https://github.com/WardPearce/Materialious?tab=readme-ov-file#setup
> 
> No. I simply followed this tutorial which uses Synology's builtin reverse proxy. https://mariushosting.com/how-to-install-materialious-on-your-synology-nas/

Tf this project only lauched a day ago & someone has already wrote a setup guide.

That article doesn't actually setup Materialious correctly, its missing how to modify the COR values in Synology.

If you can somehow replicate this https://github.com/WardPearce/Materialious?tab=readme-ov-file#setup in Synogoly open a new issue or PR & I'll include it in the README. But currently Synogoly is ouy of scope unless if someone else contributes a CORS guide.

**Comment by Umfs** [comment]
> > > have u configured your reverse proxy as mentioned here https://github.com/WardPearce/Materialious?tab=readme-ov-file#setup
> > 
> > 
> > No. I simply followed this tutorial which uses Synology's builtin reverse proxy. https://mariushosting.com/how-to-install-materialious-on-your-synology-nas/
> 
> Tf this project only lauched a day ago & someone has already wrote a setup guide.
> 
> That article doesn't actually setup Materialious correctly, its missing how to modify the COR values in Synology.
> 
> If you can somehow replicate this https://github.com/WardPearce/Materialious?tab=readme-ov-file#setup in Synogoly open a new issue or PR & I'll include it in the README. But currently Synogoly is out of scope unless if someone else contributes a CORS guide.

Will do, thanks for the direction.

**Comment by mariushosting** [comment]
Just add the missing headers at STEP 9 and everything will works as expected.

Access-Control-Allow-Credentials true;
Access-Control-Allow-Origin 
Access-Control-Allow-Methods "GET, Access-Control-Allow-Headers "User-Agent, Authorization, Content-Type" always;

**Comment by eduardo579** [comment]
> Just add the missing headers at STEP 9 and everything will works as expected.
> 
> Access-Control-Allow-Credentials true; Access-Control-Allow-Origin Access-Control-Allow-Methods "GET, Access-Control-Allow-Headers "User-Agent, Authorization, Content-Type" always;
> 
> and make sure STEP 13 is followed correctly.
> 
> I can login without any issue. So Materialious is working as expected on Synology NAS.

Hi Marius, I'm trying to run Materialous with your setup guide, could you share a screenshot of all the added headers you mention here? Adding them in step 9 solves nothing in my case. Thanks!

**Comment by Umfs** [comment]
Confirmed step#9 does not work.

**Comment by WardPearce** [comment]
Has the `Access-Control-Allow-Origin` been assigned the address of your Materialious instance? Also these headers should be added to your Invidious instance. About as much support I can give, as Materialious doesn't officially support SynogolyNAS unless if someone opens a PR

**Comment by eduardo579** [comment]
> Has the `Access-Control-Allow-Origin` been assigned the address of your Materialious instance? Also these headers should be added to your Invidious instance. About as much support I can give, as Materialious doesn't officially support SynogolyNAS unless if someone opens a PR

Yes, that header is assigned to my Invidious address, and have been added to the same Invidious instance. Thanks for your help, as is an unofficial support given by Marius, I'll wait for him to update his guide or provide us a more detailed answer.
