### ISSUE TITLE
Subscriptions in materialio.us shows "No results :(" 

### ISSUE THREAD

**Issue by hamzashahid-blit** [WardPearce/Materialious#86]
Hello there! 
Firstly, I wanted to thank you for the wonderful project and initiative! I was eager to use this service but was soon faced by an issue; When I signed up on [materialio.us](https://materialio.us), I synced subscriptions from a NewPipe file. This worked wonderfully and clicking on manage subscriptions (in [materialio.us](https://materialio.us)) or even going to the subscriptions tab in [invidious.materialio.us](https://invidious.materialio.us) works as expected. Unfortunately however, the subscriptions tab in [materialio.us](https://materialio.us) shows "No results :(" and a loading icon stays on the screen.

Thanks again and regards,
Hamza

**Comment by WardPearce** [comment]
Thank you for your interest, I'll investigate this shorty

**Comment by WardPearce** [comment]
Thanks for your issue, I've investigated importing a data via a Invidious export file & the subscription feed worked as expected. This makes me believe this might be a downstream issue with how Invidious populates the feed API after someone imports data via a NewPipe file. Maybe open a issue on Invidious or ask in their element chat.

**Comment by hamzashahid-blit** [comment]
I checked again, and it works now! Thank you for your kind cooperation.

Regards,
Hamza

**Comment by WardPearce** [comment]
> I checked again, and it works now! Thank you for your kind cooperation.
> 
> Regards, Hamza

odd, might of been due to some YT rate limiting issues the materialio.us instance was having (no resolved btw)

**Comment by hamzashahid-blit** [comment]
Yes, the invidious instance was also down for a while...

**Comment by WardPearce** [comment]
Yea the IPV6 rotation wasn't working correctly, causing YT to block us. Should be fine now.
